version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfiles/frontend.dockerfile
      args:
        ENVIRONMENT: development # Change to 'production' for production builds
    container_name: E-learning-front
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfiles/backend.dockerfile
    container_name: E-learning-back
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
